[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flowing"
version = "0.1.0"
description = "Interoperability and observability layer for multi-agent AI systems"
readme = "README.md"
authors = [
    { name = "JoaquÃ­n Gabriel Arias" }
]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
